/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jakoza (https://sketchfab.com/Moe.T)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/king-floor-bed-6ee7831cc521471384191baea365e211
Title: King Floor Bed
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bed(props) {
  const { nodes, materials } = useGLTF('/king_floor_bed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/king_floor_bed.glb')