/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jimbogies (https://sketchfab.com/jimbogies)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/building-hallway-ac43a501050149f396729bdaa4a308fb
Title: Building Hallway
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export  function Office(props) {
  const { nodes, materials } = useGLTF('/building_hallway (1).glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2.geometry}
          material={materials['Plastic02-basecolor']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_1.geometry}
          material={materials.Foundation01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_2.geometry}
          material={materials.Stucco01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_3.geometry}
          material={materials['Tiles07-basecolor']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_4.geometry}
          material={materials.Ceiling01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_5.geometry}
          material={materials['Metal04-basecolor']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_6.geometry}
          material={materials['Metal01-basecolor']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_7.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_8.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_1.geometry}
          material={materials.Light}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/building_hallway (1).glb')
